### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by gokriznastic** [gokriznastic/twitter-sentiment_mining#1]
I started this project at the start of this year with the objective to mine live tweets from twitter and get something more than binary sentiments i.e. positive or negative. The least that could be done in my opinion is to get valuable insights from the large amount of free data that is available. 

I've written some functions to mine meaningful text from among the tweets, which can be further improved in am not wrong.

Some extended usages of the `json` data collected also comes to my mind like creating insights from the geo-location data in the tweets etc. 

I had hit kind of dead end in this pursuit due to other commitments. If you're interested in NLP or data etc. and have some interesting ideas regarding what can be done with this data (except sentiment mining) or would like to collaborate on this please reply to this thread.

Thanks!

**Comment by TimPreble** [comment]
Hi, I am interested in this as I have always thought twitter to be a rich data source & have done a couple of node js projects with it.  Not sure how I can help...I have given NLP some thought but don't know much about it.  do you have any specifics you are trying to achieve?

**Comment by gokriznastic** [comment]
@TimPreble thank you for showing interest in this project! 
Any contribution helps, just feel freeto discuss any ideas and suggestions you might have. And don't worry about NLP, we'll figure it out together! If you need any help just ask here. 

As to what specifically we're trying to achieve can be found in this thread: #2 
Currently we're just tossing around ideas and see which direction can we go with the data that we collect. We hope to make a checklist and resume this soon. Pitch in!

**Comment by gokriznastic** [comment]
I would invite anyone who is interested in this project to refer the thread #2 
Sorry the discussions could not be contained to this thread! :)
